name: Project Feedback

on:
  push:
    branches:
      - main
    paths:
      - project/**

jobs:
  project-feedback:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v3
        with:
          path: main

      - name: Check out code
        uses: actions/checkout@v2

      # Install python
      - name: Set up Python 3.11
        uses: actions/setup-python@v4
        with:
          python-version: 3.11

      # Run project feedback
      - name: Project feedback
        run: |
          chmod +x project/datapipline_test.sh
          ./project/datapipline_test.sh
